#!/bin/bash
# Backend Connection Test Script
# Run this to test if the backend is working

echo "========================================"
echo "GYM APP BACKEND CONNECTION TEST"
echo "========================================"
echo ""

BASE_URL="https://yamenmod91.pythonanywhere.com"

# Test 1: Check if backend is accessible
echo "Test 1: Checking backend accessibility..."
echo "URL: $BASE_URL/api/auth/login"
HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" -X GET "$BASE_URL/api/auth/login")

if [ "$HTTP_CODE" == "405" ] || [ "$HTTP_CODE" == "200" ]; then
    echo "✅ Backend is accessible (HTTP $HTTP_CODE)"
else
    echo "❌ Backend not accessible (HTTP $HTTP_CODE)"
    echo "   This could mean:"
    echo "   - Backend server is down"
    echo "   - Network connection issue"
    echo "   - URL is incorrect"
    exit 1
fi

echo ""
echo "========================================"
echo "Test 2: Login Test"
echo "========================================"
echo "Enter your credentials:"
read -p "Username: " USERNAME
read -sp "Password: " PASSWORD
echo ""

# Test 2: Try to login
echo "Attempting login..."
LOGIN_RESPONSE=$(curl -s -X POST "$BASE_URL/api/auth/login" \
  -H "Content-Type: application/json" \
  -d "{\"username\": \"$USERNAME\", \"password\": \"$PASSWORD\"}")

# Check if token is in response
if echo "$LOGIN_RESPONSE" | grep -q "token"; then
    echo "✅ Login successful!"
    TOKEN=$(echo "$LOGIN_RESPONSE" | grep -o '"token":"[^"]*' | cut -d'"' -f4)
    echo "Token: ${TOKEN:0:20}..."

    echo ""
    echo "========================================"
    echo "Test 3: Registration Test"
    echo "========================================"
    echo "Testing customer registration..."

    # Test 3: Try to register a test customer
    REGISTER_RESPONSE=$(curl -s -X POST "$BASE_URL/api/customers/register" \
      -H "Content-Type: application/json" \
      -H "Authorization: Bearer $TOKEN" \
      -d '{
        "full_name": "Test Customer",
        "age": 25,
        "weight": 75.0,
        "height": 1.75,
        "gender": "male",
        "phone": "01234567890",
        "email": "test@test.com",
        "branch_id": 1,
        "bmi": 24.49,
        "bmi_category": "Normal",
        "bmr": 1750.0,
        "daily_calories": 2450.0
      }')

    HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" -X POST "$BASE_URL/api/customers/register" \
      -H "Content-Type: application/json" \
      -H "Authorization: Bearer $TOKEN" \
      -d '{
        "full_name": "Test Customer",
        "age": 25,
        "weight": 75.0,
        "height": 1.75,
        "gender": "male",
        "phone": "01234567890",
        "email": "test@test.com",
        "branch_id": 1,
        "bmi": 24.49,
        "bmi_category": "Normal",
        "bmr": 1750.0,
        "daily_calories": 2450.0
      }')

    if [ "$HTTP_CODE" == "200" ] || [ "$HTTP_CODE" == "201" ]; then
        echo "✅ Registration successful! (HTTP $HTTP_CODE)"
        echo ""
        echo "Response:"
        echo "$REGISTER_RESPONSE" | python3 -m json.tool 2>/dev/null || echo "$REGISTER_RESPONSE"

        # Check if QR code is generated
        if echo "$REGISTER_RESPONSE" | grep -q "qr_code"; then
            echo ""
            echo "✅ QR code is being generated by backend"
            QR_CODE=$(echo "$REGISTER_RESPONSE" | grep -o '"qr_code":"[^"]*' | cut -d'"' -f4)
            echo "QR Code: $QR_CODE"
        else
            echo ""
            echo "⚠️  Warning: No qr_code in response"
            echo "   Backend should generate QR code from customer ID"
        fi
    else
        echo "❌ Registration failed! (HTTP $HTTP_CODE)"
        echo ""
        echo "Response:"
        echo "$REGISTER_RESPONSE" | python3 -m json.tool 2>/dev/null || echo "$REGISTER_RESPONSE"
    fi
else
    echo "❌ Login failed!"
    echo ""
    echo "Response:"
    echo "$LOGIN_RESPONSE" | python3 -m json.tool 2>/dev/null || echo "$LOGIN_RESPONSE"
    echo ""
    echo "Please check:"
    echo "  - Username and password are correct"
    echo "  - Backend authentication endpoint is working"
fi

echo ""
echo "========================================"
echo "Test Complete"
echo "========================================"
echo ""
echo "Summary:"
echo "- If all tests pass ✅, your backend is working correctly"
echo "- If registration fails ❌, check the error message above"
echo "- If login fails ❌, verify your credentials"
echo ""
echo "Copy the output above and share if you need help debugging"
